PacificBiosciences/pitchfork

ports/thirdparty/zlib/Makefile
TODO - avoid cmake for now, use pkgsrc style makefile.
=> do-gitclone for zlib

Makefile, ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile
=> blasr+pbbam

Makefile, bin/checkCC, mk/sanity.mk, ports/pacbio/pbbam/Makefile, ports/pacbio/pbccs/Makefile
=> MFC - pbbam issue

README.md, ports/pacbio/pbccs/Makefile
=> MFC - pbccs issue

.travis.yml, ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/pbbam/Makefile, ports/thirdparty/ccache/Makefile
Also uncover problem in the setting
=> trying to solve this Mac issue

ports/thirdparty/swig/MD5SUM, ports/thirdparty/swig/Makefile
The problem is that LDFLAGS is poorly parsed.
=> swig+prec.h = trouble.

Makefile, ports/thirdparty/zlib/MD5SUM, ports/thirdparty/zlib/Makefile
on internal cluster some cpu features are not enabled for reliable compilation of cloudflare zlib
=> use more generic zlib

Makefile
So users don't erase stuff accidentally.
=> Vladimir suggests a _startover prompt

Makefile, mk/config.mk, mk/sanity.mk, ports/pacbio/blasr/Makefile, ports/pacbio/blasr/patch-01, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/blasr_libcpp/patch-01
I had a brain-fart, almost screwed this branch...
=> MFC - Alpine Linux

ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/htslib/Makefile, ports/pacbio/pbbam/Makefile, ports/pacbio/pbccs/Makefile, ports/pacbio/pbdagcon/Makefile, ports/pacbio/pblaa/Makefile, ports/pacbio/ppa/Makefile, ports/thirdparty/samtools/Makefile
=> pacbio htslib back to prefix/lib, prefix/include

Makefile, ports/pacbio/ConsensusCore/Makefile, ports/pacbio/ConsensusCore2/Makefile, ports/pacbio/GenomicConsensus/Makefile, ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/daligner/Makefile, ports/pacbio/dazzdb/Makefile, ports/pacbio/falcon_kit/Makefile, ports/pacbio/htslib/Makefile, ports/pacbio/kineticsTools/Makefile, ports/pacbio/pbalign/Makefile, ports/pacbio/pbbam/Makefile, ports/pacbio/pbccs/Makefile, ports/pacbio/pbchimera/Makefile, ports/pacbio/pbcommand/Makefile, ports/pacbio/pbcore/Makefile, ports/pacbio/pbcoretools/Makefile, ports/pacbio/pbdagcon/Makefile, ports/pacbio/pbdoctorb/Makefile, ports/pacbio/pbfalcon/Makefile, ports/pacbio/pblaa/Makefile, ports/pacbio/pbreports/Makefile, ports/pacbio/pbsmrtpipe/Makefile, ports/pacbio/pbsparse/Makefile, ports/pacbio/pypeFLOW/Makefile, ports/pacbio/seqan/Makefile
but now pbcss would depend on python stuff...
=> REPO settings and pbccs

Makefile, README.md, mk/init.mk, mk/pitchfork.mk
make init
make -j world
There are still other problems with multi-job builds, but this gets us closer.
=> Initialize separately

Makefile, ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/pbbam/Makefile
```
$ time make -j blasr |& tee out.log
real    5m48.039s
user    36m1.302s
sys     37m12.420s
```
Not sure whether that used ccache from build on other machine.
=> multi-job for blasr/libcpp/pbbam

ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile
Btw, I've also fixed all the blasr warnings, in the blasr repo itself.
=> Blasr: fix multi-job; do-clean; do-build

mk/config.mk, ports/pacbio/blasr/Makefile, ports/pacbio/pbbam/Makefile, ports/pacbio/pbccs/Makefile, ports/python/matplotlib/Makefile, ports/thirdparty/python/Makefile, ports/thirdparty/samtools/Makefile
=> Found the problem of double include

mk/config.mk, ports/python/cython/Makefile, ports/python/virtualenv/Makefile
=> combining python + osx + virtualenv makes me sad

Makefile, ports/pacbio/Cogent/Makefile, ports/python/PuLP/Makefile, ports/python/bx-python/Makefile, ports/python/dask.array/Makefile, ports/python/pillow/Makefile, ports/python/scikit-image/Makefile, ports/python/toolz/Makefile, ports/thirdparty/mash/MD5SUM, ports/thirdparty/mash/Makefile, ports/thirdparty/ssw_lib/Makefile
=> Cogent dump

Makefile, bin/pitchfork, ports/thirdparty/ccache/Makefile, ports/thirdparty/samtools-1.3.1/MD5SUM, ports/thirdparty/samtools-1.3.1/Makefile, ports/thirdparty/samtools-1.3.1/patch-01
=> fetch model, ln arguments, a port for test

ports/pacbio/ConsensusCore2/Makefile, ports/pacbio/pbccs/Makefile, ports/pacbio/pblaa/Makefile
pbccs/pblaa should now load the dynamic lib
=> Libpbconsensus.dylib

ports/thirdparty/ncurses/Makefile
cdunn> make ncurses` repeats everytime I run `make`.
cdunn> I use `HAVE_NCURSES`, so this only takes a minute, but it's annoying.
=> check for the installed ncurses

ports/pacbio/pbcommandr/Makefile
=> update the folders to find

bin/pitchfork
Will merge after finishing the next feature.
=> fetch should crash upon md5sum failure.

bin/pitchfork, bin/travisbuild.sh, bin/travistest.sh
I am terribly sorry that I broke the master build. Should be fixed now.
=> Fetch refactor

ports/python/virtualenv/Makefile
=> upgrading pip seems dangerous now

.gitignore, .travis.yml, bin/travisbuild.sh, mk/config.mk
It's still possible to put them in pitchfork/.git/pip ...
=> simplifying the path of pip cache

.travis.yml, bin/pitchfork
=> hotfix fetching code brain fart

.gitignore, README.md, settings.mk
I have not tested this yet, so don't pull. I need a working pitchfork first. (Working with MJ in Slack.)
=> PF_SETTINGS_MK

bin/pitchfork
=> Checked backticks

ports/thirdparty/ncurses/Makefile
https://github.com/PacificBiosciences/pitchfork/issues/287
=> issue #287

Makefile, ports/pacbio/dextractor/Makefile
Based on #303, so please merge that one first.
=> dextractor (from thegenemyers)

Makefile, ports/pacbio/FALCON_unzip/Makefile, ports/pacbio/blasr/Makefile, ports/pacbio/blasr_libcpp/Makefile, ports/pacbio/pbalign/Makefile, ports/pacbio/pbbam/Makefile
=> legacy pbalign

bin/checkCC, bin/checkFC
=> resolving issue #314

bin/pitchfork, bin/uninstall, ports/pacbio/pbcopper/Makefile
=> pitchfork uninstall becomes less retarded

ports/thirdparty/readline/Makefile
https://github.com/PacificBiosciences/pitchfork/issues/316
=> Fixing readline compilation on ubuntu15 and ubuntu16

.gitignore, bin/_argparse.py, bin/pitchfork, bin/secondary, ports/python/matplotlib/Makefile
=> Pitchfork python

Makefile, ports/python/numpy/MD5SUM, ports/python/pysam/Makefile, ports/thirdparty/bamtools/MD5SUM, ports/thirdparty/bamtools/Makefile
=> WIP: pysam version + bamtools

Makefile, ports/pacbio/pbdagcon/Makefile
https://github.com/PacificBiosciences/pitchfork/issues/331
=> adding GTEST_SRC/GTEST_INCLUDE

Makefile, ports/pacbio/trim_isoseq_polyA/Makefile, ports/thirdparty/libbzip2/MD5SUM, ports/thirdparty/libbzip2/Makefile
https://github.com/PacificBiosciences/pitchfork/issues/343
=> using libbzip2 for trim_isoseq_polyA

Makefile, bin/checkCC, bin/checkCXX, bin/checkFC, bin/pitchfork, mk/config.mk, mk/travis.mk
https://github.com/PacificBiosciences/pitchfork/issues/341
=> Ccache off

ports/thirdparty/boost/Makefile, ports/thirdparty/ccache/Makefile, ports/thirdparty/hdf5/Makefile, ports/thirdparty/ncurses/Makefile, ports/thirdparty/openblas/Makefile, ports/thirdparty/zlib/Makefile
https://github.com/PacificBiosciences/pitchfork/issues/350
=> Remove the version from _NAME for prebuilt port

mk/config.mk, ports/pacbio/htslib/Makefile, ports/pacbio/pbdagcon/Makefile, ports/thirdparty/samtools/Makefile
Only needed in some combination of compiler + linker.
=> hotfix - cflags for GNU ld

Makefile, mk/config.mk, ports/pacbio/htslib/Makefile, ports/thirdparty/boost/Makefile, ports/thirdparty/ccache/Makefile, ports/thirdparty/cmake/Makefile, ports/thirdparty/gmap/Makefile, ports/thirdparty/hdf5/Makefile, ports/thirdparty/hmmer/Makefile, ports/thirdparty/libpng/Makefile, ports/thirdparty/libressl/Makefile, ports/thirdparty/ncurses/Makefile, ports/thirdparty/openblas/Makefile, ports/thirdparty/readline/Makefile, ports/thirdparty/samtools-0.1.20/Makefile, ports/thirdparty/samtools/Makefile, ports/thirdparty/ssw_lib/Makefile, ports/thirdparty/swig/Makefile, ports/thirdparty/zlib/Makefile
=> Prebuilt option

mk/config.mk
https://github.com/PacificBiosciences/blasr/issues/332
=> UGLY FIX - clash with module author
